version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kvado
      MYSQL_USER: kvado
      MYSQL_PASSWORD: password
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

